//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushToITCL.SIBLCBS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SIBLCBS.SIBLATSSoap")]
    public interface SIBLATSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doCTSTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PushToITCL.SIBLCBS.transactionResponse doCTSTransaction(string sFromAccount, string sToAccount, string sAmount, string sCharges, string Narration, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno, string sRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doCTSTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<PushToITCL.SIBLCBS.transactionResponse> doCTSTransactionAsync(string sFromAccount, string sToAccount, string sAmount, string sCharges, string Narration, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno, string sRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doCTSReverseTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PushToITCL.SIBLCBS.transactionResponse doCTSReverseTransaction(string sFromAccount, string sToAccount, string sAmount, string sRequestId, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doCTSReverseTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<PushToITCL.SIBLCBS.transactionResponse> doCTSReverseTransactionAsync(string sFromAccount, string sToAccount, string sAmount, string sRequestId, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PushToITCL.SIBLCBS.AccountInformationResponse GetAccountDetail(string sAccountNumber, string referenceno, string sRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<PushToITCL.SIBLCBS.AccountInformationResponse> GetAccountDetailAsync(string sAccountNumber, string referenceno, string sRequestId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public enum accountType {
        
        /// <remarks/>
        Savings,
        
        /// <remarks/>
        Checking,
        
        /// <remarks/>
        Gl,
        
        /// <remarks/>
        SubGL,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AccountInformationResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public partial class transactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private errorDetail errorDetailField;
        
        private string requestReferenceField;
        
        private string responseReferenceField;
        
        private transactionStatus transactionStatusField;
        
        private bool transactionStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public errorDetail errorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
                this.RaisePropertyChanged("errorDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string requestReference {
            get {
                return this.requestReferenceField;
            }
            set {
                this.requestReferenceField = value;
                this.RaisePropertyChanged("requestReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string responseReference {
            get {
                return this.responseReferenceField;
            }
            set {
                this.responseReferenceField = value;
                this.RaisePropertyChanged("responseReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public transactionStatus transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionStatusSpecified {
            get {
                return this.transactionStatusFieldSpecified;
            }
            set {
                this.transactionStatusFieldSpecified = value;
                this.RaisePropertyChanged("transactionStatusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public partial class errorDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public partial class AccountSignature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public partial class AccountDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal accountBalanceField;
        
        private bool accountBalanceFieldSpecified;
        
        private string accountNameField;
        
        private string accountNumberField;
        
        private string accountStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal accountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
                this.RaisePropertyChanged("accountBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountBalanceSpecified {
            get {
                return this.accountBalanceFieldSpecified;
            }
            set {
                this.accountBalanceFieldSpecified = value;
                this.RaisePropertyChanged("accountBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("accountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string accountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
                this.RaisePropertyChanged("accountStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public enum transactionStatus {
        
        /// <remarks/>
        FAIL,
        
        /// <remarks/>
        SUCCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ababil.mislbd.com/ws/api")]
    public partial class AccountInformationResponse : transactionResponse {
        
        private AccountDetail accountDetailField;
        
        private AccountSignature[] signaturesField;
        
        private string signatureInstructionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AccountDetail accountDetail {
            get {
                return this.accountDetailField;
            }
            set {
                this.accountDetailField = value;
                this.RaisePropertyChanged("accountDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signatures", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public AccountSignature[] signatures {
            get {
                return this.signaturesField;
            }
            set {
                this.signaturesField = value;
                this.RaisePropertyChanged("signatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string signatureInstruction {
            get {
                return this.signatureInstructionField;
            }
            set {
                this.signatureInstructionField = value;
                this.RaisePropertyChanged("signatureInstruction");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SIBLATSSoapChannel : PushToITCL.SIBLCBS.SIBLATSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIBLATSSoapClient : System.ServiceModel.ClientBase<PushToITCL.SIBLCBS.SIBLATSSoap>, PushToITCL.SIBLCBS.SIBLATSSoap {
        
        public SIBLATSSoapClient() {
        }
        
        public SIBLATSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIBLATSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIBLATSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIBLATSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PushToITCL.SIBLCBS.transactionResponse doCTSTransaction(string sFromAccount, string sToAccount, string sAmount, string sCharges, string Narration, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno, string sRequestId) {
            return base.Channel.doCTSTransaction(sFromAccount, sToAccount, sAmount, sCharges, Narration, fromAccountType, toAccountType, referenceno, sRequestId);
        }
        
        public System.Threading.Tasks.Task<PushToITCL.SIBLCBS.transactionResponse> doCTSTransactionAsync(string sFromAccount, string sToAccount, string sAmount, string sCharges, string Narration, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno, string sRequestId) {
            return base.Channel.doCTSTransactionAsync(sFromAccount, sToAccount, sAmount, sCharges, Narration, fromAccountType, toAccountType, referenceno, sRequestId);
        }
        
        public PushToITCL.SIBLCBS.transactionResponse doCTSReverseTransaction(string sFromAccount, string sToAccount, string sAmount, string sRequestId, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno) {
            return base.Channel.doCTSReverseTransaction(sFromAccount, sToAccount, sAmount, sRequestId, fromAccountType, toAccountType, referenceno);
        }
        
        public System.Threading.Tasks.Task<PushToITCL.SIBLCBS.transactionResponse> doCTSReverseTransactionAsync(string sFromAccount, string sToAccount, string sAmount, string sRequestId, PushToITCL.SIBLCBS.accountType fromAccountType, PushToITCL.SIBLCBS.accountType toAccountType, string referenceno) {
            return base.Channel.doCTSReverseTransactionAsync(sFromAccount, sToAccount, sAmount, sRequestId, fromAccountType, toAccountType, referenceno);
        }
        
        public PushToITCL.SIBLCBS.AccountInformationResponse GetAccountDetail(string sAccountNumber, string referenceno, string sRequestId) {
            return base.Channel.GetAccountDetail(sAccountNumber, referenceno, sRequestId);
        }
        
        public System.Threading.Tasks.Task<PushToITCL.SIBLCBS.AccountInformationResponse> GetAccountDetailAsync(string sAccountNumber, string referenceno, string sRequestId) {
            return base.Channel.GetAccountDetailAsync(sAccountNumber, referenceno, sRequestId);
        }
    }
}
